### ISSUE TITLE
Transfer to tc39-transfer

### ISSUE THREAD

**Issue by ljharb** [tc39-transfer/proposal-string-dedent#14]
Please follow the instructions [here](https://github.com/tc39/proposals#onboarding-existing-proposals) to transfer the repo.

I've sent @mmkal an invite to the tc39-transfer org.

**Comment by jridgewell** [comment]
Hi @mmkal! TC39 has [accepted this as a Stage 1 proposal](https://github.com/babel/proposals/issues/69#issuecomment-697128456), and part of that process is transferring it so that it's owned by the tc39 org.

**Comment by mmkal** [comment]
Awesome news! Will transfer today

**Comment by ljharb** [comment]
@mmkal also, you may want to rename either the repo, or the entry in the proposals table, so they match. The agenda used "String.dedent", so that's what I used in the proposals table (in which case, `proposal-string-dedent` or similar).

**Comment by mmkal** [comment]
@ljharb renamed and transferred - let me know if there are any teams I need to add/anything else I should do re ownership.
